const actionType = {
    GET_ALL_SCHEDULE_BEGIN: "GET_ALL_SCHEDULE_BEGIN",
    GET_ALL_SCHEDULE_SUCCESS: "GET_ALL_SCHEDULE_SUCCESS",
    GET_ALL_SCHEDULE_FAILURE: "GET_ALL_SCHEDULE_FAILURE",

    ADD_SCHEDULE_BEGIN: "ADD_SCHEDULE_BEGIN",
    ADD_SCHEDULE_SUCCESS: "ADD_SCHEDULE_SUCCESS",
    ADD_SCHEDULE_FAILURE: "ADD_SCHEDULE_FAILURE",

    GET_SCHEDULE_BEGIN: "GET_SCHEDULE_BEGIN",
    GET_SCHEDULE_SUCCESS: "GET_SCHEDULE_SUCCESS",
    GET_SCHEDULE_FAILURE: "GET_SCHEDULE_FAILURE",

    EDIT_SCHEDULE_BEGIN: "EDIT_SCHEDULE_BEGIN",
    EDIT_SCHEDULE_SUCCESS: "EDIT_SCHEDULE_SUCCESS",
    EDIT_SCHEDULE_FAILURE: "EDIT_SCHEDULE_FAILURE",

    DELETE_SCHEDULE_BEGIN: "DELETE_SCHEDULE_BEGIN",
    DELETE_SCHEDULE_SUCCESS: "DELETE_SCHEDULE_SUCCESS",
    DELETE_SCHEDULE_FAILURE: "DELETE_SCHEDULE_FAILURE",

    LOADING_REQUEST: "LOADING_REQUEST",

    CHANGE_STATE_SCHEDULE: "CHANGE_STATE_SCHEDULE",
    CHANGE_BOOKMARK_SCHEDULE: "CHANGE_BOOKMARK_SCHEDULE" 
};

export default actionType;
