const actionType = {
    REMOVE_SCHEDULE: "REMOVE_SCHEDULE",
    EDIT_SCHEDULE: "EDIT_SCHEDULE",

    GET_ALL_SCHEDULE_BEGIN: "GET_ALL_SCHEDULE_BEGIN",
    GET_ALL_SCHEDULE_SUCCESS: "GET_ALL_SCHEDULE_SUCCESS",
    GET_ALL_SCHEDULE_FAILURE: "GET_ALL_SCHEDULE_FAILURE",

    ADD_SCHEDULE_BEGIN: "ADD_SCHEDULE_BEGIN",
    ADD_SCHEDULE_SUCCESS: "ADD_SCHEDULE_SUCCESS",
    ADD_SCHEDULE_FAILURE: "ADD_SCHEDULE_FAILURE",

    TOGGLE_SCHEDULE: "TOGGLE_SCHEDULE"
};

export default actionType;
